### ISSUE TITLE
Develop basic Wit.ai Interface

### ISSUE THREAD

**Issue by vishalkuo** [dulwin/ezebot#4]
We would like to have Jarvis to handle more natural queries such as `hey Jarvis, what's the doorcode for...` instead of rigid requirements like `Jarvis doorcode ...`.

As a result, we have decided to use wit.ai to handle intent processing on our behalf. Given a query, wit.ai should be able to provide us with something along the following lines:

``` JSON
{
  "action": "doorcode",
  "value": 123456
}
```

Ideally, we can use some sort of Go reflection to get an instance of our desired handler based on the action name alone (instead of a large match statement). We can further use Go inheritance to enforce structure on our intent handlers.

**Comment by tanatorn** [comment]
#10
