### ISSUE TITLE
Setup sqlite3 and gorm

### ISSUE THREAD

**Issue by vishalkuo** [dulwin/ezebot#5]
Us poor students need to persist Jarvis' responses to queries in a consistent and dependable manner. We have decided to use sqlite3 as our storage layer as this is light weight and we can share the files if need be. However, for ease of use, we should add [gorm](https://github.com/jinzhu/gorm) to our project. 

Sub-tasks include
1) Developing a singleton or factory entity manager so that the database is easily accessible from anywhere throughout the project
2) Deciding on a handler model structure and implementing / testing with gorm 
3) Integrating with wit.ai/whatever intent handler we use. This will need some coordination with @tanatornn96

**Comment by tanatorn** [comment]
Definitely check out go's `init()` function and package namespaces, ie. variables in same package can be accessed across different files.

**Comment by vishalkuo** [comment]
After consideration, lets switch to Postgres. I'm assuming everyone can set it up on their machines and gorm should handle migrations. Furthermore, Heroku provides Postgres for free anyways. Finally, this saves us from having to commit a binary sqlite file which will inevitably grow unwieldy.

**Comment by vishalkuo** [comment]
#12
